version: '3.8'
services:
  nginx:
    container_name: nginx-php
    image: richarvey/nginx-php-fpm:latest
    hostname: __DOCKER_PHP_FPM__
    ports:
      - "80:80"
    volumes:
      - ./app:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/conf.d/:/etc/nginx/conf.d/:rw
      - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:rw

  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql:/tmp/sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456